
workspace 'UIExamples'

xcodeproj 'MLUICoreExample/MLUICoreExample.xcodeproj'
    
target :MLUIRedCircleViewExample do
    xcodeproj 'MLUIRedCircleViewExample/MLUIRedCircleViewExample.xcodeproj'
    pod "MLUI/RedCircleView", :path => "../"

end

