
workspace 'UIExamples'

xcodeproj 'MLUIComponents/MLUIComponents.xcodeproj'


#target :MLUIComponents do
#    xcodeproj 'MLUIComponents/MLUIComponents.xcodeproj'
#    pod "MLUI", :path => "../"
#end


pod "MLUI", :path => "../"
#pod 'KIF', '3.0.7'
#pod 'OCMock', '3.0.2'
#pod 'XCTAsyncTestCase', '0.1.0'




#target :MLUIRedCircleViewExample do
#    xcodeproj 'MLUIRedCircleViewExample/MLUIRedCircleViewExample.xcodeproj'
#    pod "MLUI/RedCircleView", :path => "../"
#    pod "MLUI/ParalelogramView", :path => "../"
#    pod "AFNetworking" , '2.4.1'
#
#end


